homework_10/homework_10/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from users.views import loginuser

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('quotes.urls')),
    path('users/', include('users.urls')),
    path('verification/', include('verify_email.urls')),
    path('login/', loginuser, name='login'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homework_10/quotes/urls.py
from django.urls import path
from . import views

app_name = 'quotes'

urlpatterns = [
    path('', views.main, name='main'),
    path('index/', views.main, name='index'),
    path('author/', views.author, name='author'),
    path('author_detail/<int:author_id>', views.author_datail, name='author_detail'),
    path('tag/', views.tag, name='tag'),
    path('quote/', views.quote, name='quote'),
    path("quote/<int:pk>/update", views.UpdateQuote.as_view(), name="quote_update"),
    path("quote/quote_add_tag/<int:quote_id>", views.quote_add_tag, name="quote_add_tag"),
    path('detail/<int:quote_id>', views.detail, name='detail'),
    path('quote_hide/<int:quote_id>', views.quote_hide, name='quote_hide'),
    path('done/<int:quote_id>', views.set_done, name='set_done'),
    path('delete/<int:quote_id>', views.delete_quote, name='delete'),
    path('search_by_tag/<str:tag_name>/', views.search_by_tag, name='search_by_tag'),
    path('author_seeds/', views.authors_seeds_from_mongodb, name='author_seeds'),
    path('quote_seeds/', views.quotes_seeds_from_mongodb, name='quote_seeds'),
    path('tags_seeds/', views.tags_seeds_from_mongodb, name='tags_seeds'),
    path('migrate_from_mongo_to_postger/', views.migrate_from_mongo_to_postger, name='migrate_from_mongo_to_postger')
]

homework_10/users/urls.py
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

homework_10/quotes/models.py
from typing import Any
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Tag(models.Model):
    name = models.CharField(max_length=70, null=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user', 'name'], name='tag of username')
        ]

    def __str__(self):
        return f"{self.name}"


class Author(models.Model):
    full_name = models.CharField(max_length=100)
    born_date = models.DateTimeField()
    born_location = models.CharField(max_length=255)
    description = models.CharField(max_length = 2704)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user','full_name', 'born_date', 'born_location', 'description'], name='author of username')
        ]

    def __str__(self) -> str:
        return self.full_name
    

class Quote(models.Model):
    description = models.CharField(null=False)
    done = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    tags = models.ManyToManyField(Tag)
    author = models.ManyToManyField(Author)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return f"{self.author}"

homework_10/quotes/forms.py
from datetime import date

from django.forms import (Form,
                        ModelForm,
                        CharField,
                        TextInput,
                        DateField,
                        ModelMultipleChoiceField,
                        SelectMultiple,
                        SelectDateWidget)

from .models import Tag, Quote, Author


class TagForm(ModelForm):

    name = CharField(min_length=3, max_length=25, required=True, widget=TextInput())
    
    class Meta:
        model = Tag
        fields = ['name']
        
class QuoteForm(ModelForm):

    description = CharField(min_length=10, required=True, widget=TextInput())

    class Meta:
        model = Quote
        exclude = ['author']
        exclude = ['tags']
        fields = ['description']


class AuthorForm(ModelForm):

    full_name = CharField(min_length=5, max_length=100, required=True, widget=TextInput())
    born_date = DateField(widget=SelectDateWidget(years=range(1700, int(date.today().strftime("%Y"))+1),empty_label=("Select year","Select month","Select day")))
    born_location = CharField(min_length=6, max_length=255, required=True, widget=TextInput())
    description = CharField(widget=TextInput())

    class Meta:
        model = Author
        fields = ['full_name', 'born_date', 'born_location', 'description']

class QuoteAddTag(Form):

    new_tag = ModelMultipleChoiceField(queryset=Tag.objects.all(), required=False, widget=SelectMultiple())

homework_10/quotes/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.views.generic.edit import UpdateView
from django.urls import reverse_lazy
from django.db.models import Count
from django.db.utils import OperationalError, IntegrityError

from .connect_mongo import authors_from_mongodb, quotes_from_mongodb
from .forms import TagForm, QuoteForm, AuthorForm, QuoteAddTag
from .models import Tag, Quote, Author



def main(request):
    quotes_list = Quote.objects.all().order_by('-created')
    number_of_quotes_in_page = 10
    paginator = Paginator(quotes_list, number_of_quotes_in_page)
    page = request.GET.get('page')
    top_tags = get_top_ten_tags()

    try:
        quotes = paginator.page(page)
    except PageNotAnInteger:
        quotes = paginator.page(1)
    except EmptyPage:
        quotes = paginator.page(paginator.num_pages)

    context = {
        'top_tags': top_tags,
        'quotes': quotes
    }

    return render(request, 'quotes/index.html', context=context)

class UpdateQuote(UpdateView):
    model = Quote
    fields = ["description"]
    template_name_suffix = "_update_form"
    success_url = reverse_lazy('quotes:main')

def quote_add_tag(request, quote_id):
    quote = get_object_or_404(Quote, pk=quote_id)
    tags = Tag.objects.all()
    if request.method == 'POST':
        form = QuoteAddTag(request.POST)
        if form.is_valid():
            new_tag = form.cleaned_data['new_tag'][0]
            quote.tags.add(new_tag)
            return redirect(to='quotes:main')
    else:
        form = QuoteAddTag()
    return render(request, 'quotes/quote_add_tag.html', {'form': form, 'tags': tags, 'quotes': quote})

def tag(request):
    if request.method == 'POST':
        form = TagForm(request.POST)
        if form.is_valid():
            tag = form.save(commit=False)
            tag.user = request.user
            tag.save()
            return redirect(to='quotes:main')
        else:
            return render(request, 'quotes/tag.html', {'form': form})

    return render(request, 'quotes/tag.html', {'form': TagForm()})

def search_by_tag(request, tag_name):
    quotes_list = Quote.objects.filter(tags__name=tag_name).all()
    number_of_quotes_in_page = 10
    paginator = Paginator(quotes_list, number_of_quotes_in_page)
    page = request.GET.get('page')

    try:
        quotes = paginator.page(page)
    except PageNotAnInteger:
        quotes = paginator.page(1)
    except EmptyPage:
        quotes = paginator.page(paginator.num_pages)

    return render(request, 'quotes/search_by_tag.html', {'quotes': quotes})

def detail(request, quote_id):
    '''render quote-detail page'''
    quotes = get_object_or_404(Quote, pk=quote_id)
    authors = Author.objects.all()
    return render(request, 'quotes/detail.html', {"quotes": quotes, "authors": authors})

@login_required
def set_done(request, quote_id):
    Quote.objects.filter(pk=quote_id, user=request.user).update(done=True)
    return redirect(to='quotes:main')

@login_required
def quote_hide(request, quote_id):
    Quote.objects.filter(pk=quote_id, user=request.user).update(done=False)
    return redirect(to='quotes:main')

@login_required
def delete_quote(request, quote_id):
    Quote.objects.get(pk=quote_id, user=request.user).delete()
    return redirect(to='quotes:main')

def author(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            new_author = form.save(commit=False)
            new_author.user = request.user
            new_author.save()

            return redirect(to='quotes:main')
        else:
            return render(request, 'quotes/author.html', {'form': form})

    return render(request, 'quotes/author.html', {'form': AuthorForm()})

def quote(request):
    tags = Tag.objects.all()
    authors = Author.objects.all()

    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            new_quote = form.save(commit=False)
            new_quote.user = request.user
            new_quote.save()
            choice_tags = Tag.objects.filter(name__in=request.POST.getlist('tags'), user=request.user)
            choice_author = Author.objects.filter(full_name__in=request.POST.getlist('authors'), user=request.user)
            for tag in choice_tags.iterator():
                new_quote.tags.add(tag)
            for author in choice_author.iterator():
                new_quote.author.add(author)


            return redirect(to='quotes:main')
        else:
            return render(request, 'quotes/quote.html', {"tags": tags, "authors": authors, 'form': form})

    return render(request, 'quotes/quote.html', {"tags": tags, "authors": authors, 'form': QuoteForm()})

def author_datail(request, author_id):

    author = get_object_or_404(Author, pk = author_id)
    return render(request, "quotes/author_detail.html", {"author": author})

def get_top_ten_tags():
    '''return 10 top tags'''
    top_tags = Tag.objects.annotate(num_quotes=Count('quote'))\
                          .order_by('-num_quotes')[:10]
    return top_tags

# Functions for migrate data from mongo(Hjmework 9)

def authors_seeds_from_mongodb(*args,**kwargs):
    data = authors_from_mongodb()
    for item in data:
        _description = item.get('description')
        if len(_description) > 2704:
            _description = _description[0:2704]
        try:
            Author.objects.create(full_name= item.get('full_name'),
                  born_date= item.get('born_date'),
                  born_location= item.get('born_location'),
                  description= _description)
        except (OperationalError, IntegrityError) as err:     
            print(err)
            continue


def quotes_seeds_from_mongodb(request):
    data = quotes_from_mongodb()
    for item in data:
        quote = str
        tags = []
        author = Author
        quote = item.get('quote')
        for tag in item.get('tags'):
            tags.append(Tag.objects.filter(name= tag.get('name'),user=request.user).first())
        author = Author.objects.filter(full_name= item.get('author'),user=request.user).first()
        result = Quote.objects.create(description=quote, done=True)
        result.save()
        result.author.add(author)
        for tag in tags:
            result.tags.add(tag)

        
def tags_seeds_from_mongodb(*args, **kwargs):
    data = quotes_from_mongodb()

    for item in data:
        for tag in item.get('tags'):
            try:
                Tag.objects.create(name= tag.get('name'))
            except IntegrityError as er:
                print(er)
                continue


def migrate_from_mongo_to_postger(request, *args, **kwargs):
    authors_seeds_from_mongodb(request)
    tags_seeds_from_mongodb(request)
    quotes_seeds_from_mongodb(request)
    return redirect(to="quotes:main")

homework_10/quotes/templates/quotes/author.html
{% extends "quotes/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotes:author' %}">
    {% csrf_token %}
    <div class="author-form">
        <div>
            <div>
                <label class="author-fullname-input"> Author full name:
                    {{ form.full_name }}
                </label>
                <span>{{ form.errors.full_name }}</span>
            </div>
            <div>
                <label class="author-born-location-input"> Born location:
                    {{ form.born_location }}
                </label>
                <span>{{ form.errors.born_location }}</span>
            </div>
        </div>
        <div>
            <label class="author-born-date-input"> Born date:
                {{ form.born_date }}
            </label>
            <span>{{ form.errors.born_date }}</span>
        </div>
    </div>
    <div>
        <label class="author-description-input"> Description:
            {{ form.description }}
        </label>
        <span>{{ form.errors.description }}</span>
    </div>
    <div class="grid">
        <button class="Add-Quote" type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>
{% endblock %}

homework_10/quotes/templates/quotes/author_detail.html
{% extends "quotes/base.html" %}

{% block content %}

<h1 class="autor-full-name">Author: <kbd>{{author.full_name}}</kbd></h1>
<p class="author-born-date">Born date: <kbd>{{author.born_date}}</kbd></p>
<p class="author-born-location">Born location: <kbd>{{author.born_location}}</kbd></p>
<p class="author-description">Description: <kbd>"{{author.description}}"</kbd></p>

{% endblock %}

homework_10/quotes/templates/quotes/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>Note information</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css"/>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<main class="container">
    <nav style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 30px">
        <ul>
            <li><a href="/" role="button"> Go back to the main page </a></li>
        </ul>
    </nav>
    {% block content %} {% endblock %}
</main>
</body>
</html>

homework_10/quotes/templates/quotes/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>Organizer</title>
    {% load static %}
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css"/>
    <link rel="stylesheet" href="{% static 'css/style.css' %}/">
</head>
<body>
    <nav style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 30px">
        {% if user.is_authenticated %}
        <ul>
            <li><a href="{% url 'quotes:quote' %}" role="button">Add Quote</a></li>
            <li><a href="{% url 'quotes:tag' %}" role="button">Add Tag</a></li>
            <li><a href="{% url 'quotes:author' %}" role="button">Add Author </a></li>
            {% if user.is_staff %}
            <li><a href="{% url 'quotes:migrate_from_mongo_to_postger' %}" role="button">Migrate dbs</a></li>
            {% endif %}
        </ul>
        <ul>
            <li>Welcome <b>{{ user.username }}!</b></li>
            <li><a href="{% url 'users:logout' %}" role="button">Logout</a></li>
        </ul>
        {% else %}
        <ul>
            <li><a href="{% url 'users:signup' %}" role="button">Sign Up</a></li>
            <li><a href="{% url 'users:login' %}" role="button">Login</a></li>
        </ul>
        
        {% endif %}
    </nav>
<main class="wrapper">
    <div class="main-content">
        {% load extract_tags %} 
        {% for quote in quotes %}
        <ul>
            <li class="li">
                {% if quote.done %} 
                <div class="quote-container" >
                    <div class="quote-discriotion-container">
                        <a class="description" href="{% url 'quotes:detail' quote.id %}">{{ quote.description }}</a>
                        {% if request.user == quote.user %}
                        <a class="button" href="{% url 'quotes:quote_update' quote.id %}" role="button">UPDATE</a>
                        <a class="quote-hide-button" href="{% url 'quotes:quote_hide' quote.id %}" role="button" class="secondary"><p>Hide from everyone</p></a>
                        {% endif %}
                    </div>
                    <div class="tag-container">
                        <p>Tags: </p>
                        {% for tag in quote.tags|tags_list %}
                            <a class="button" href="{%url 'quotes:search_by_tag' tag %}" role="button">{{ tag }}</a>
                        {% endfor %}
                        {% if request.user == quote.user %}
                        <a class="add-tag-button" href="{% url 'quotes:quote_add_tag' quote.id %}" role="button">Add Tag</a>
                        {% endif %}
                    </div>
                    <div class="quote-autor-info">
                        <p class="quote-author">by: {{ quote.author|author }}<a class="author-details-href" href="{% url 'quotes:author_detail' quote.author|author_id %}">(about)</a></p>
                        {% if request.user == quote.user %}
                        <button class="delete-quote" data-quote-id="{{ quote.id }}" onclick="confirmDelete(this.dataset.quoteId)">Delete</button>
                        {% endif %}
                    </div>
                </div>    
                {% else %}
                    {% if request.user == quote.user %}
                    <div class="quote-container" >
                        <div class="quote-discriotion-container">
                            <a class="description" href="{% url 'quotes:detail' quote.id %}">{{ quote.description }}</a>
                            <a class="button" href="{% url 'quotes:quote_update' quote.id %}" role="button">UPDATE</a>
                            <a class="button" href="{% url 'quotes:set_done' quote.id %}" role="button" > Post for all </a>
                        </div>
                        <div class="tag-container">
                            <p>Tags: </p>
                            {% for tag in quote.tags|tags_list %}
                                <a class="button" href="{%url 'quotes:search_by_tag' tag %}" role="button">{{ tag }}</a>
                            {% endfor %}
                            <a class="add-tag-button" href="{% url 'quotes:quote_add_tag' quote.id %}" role="button">Add Tag</a>
                        </div>
                        <div class="quote-autor-info">
                            <p class="quote-author">by: {{ quote.author|author }}<a class="author-details-href" href="{% url 'quotes:author_detail' quote.author|author_id %}">(about)</a></p>
                            <button class="delete-quote" data-quote-id="{{ quote.id }}" onclick="confirmDelete(this.dataset.quoteId)">Delete</button>
                        </div>
                    </div>
                    {% endif %} 
                {% endif %}
            </li>
        </ul>
        {% endfor %}
            
        <footer>
            <div>
                {% if quotes.has_previous %}
                <a href="?page=1" role="button">First</a>
                <a href="?page={{ quotes.previous_page_number }}" role="button">Previous</a>
                {% endif %}
                <span style="padding-left: 15px; padding-right: 15px">Page {{ quotes.number }} of {{ quotes.paginator.num_pages }}</span>
                {% if quotes.has_next %}
                <a href="?page={{ quotes.next_page_number }}" role="button">Next</a>
                <a href="?page={{ quotes.paginator.num_pages }}" role="button">Last</a>
                {% endif %}
            </div>
        </footer>
    </div>
    {% if top_tags %}
    <div class="top-ten-tags-container">
        <h2 class="h2-top-tags">Top Ten Tags</h2>
        <ul>
            {% for tag in top_tags %}
            <li class="li"><a href="{% url 'quotes:search_by_tag' tag %}">{{ tag.name }}</a> {{ tag.num_quotes }}</li>
            {% endfor %}
        </ul>
    </div>
    {% endif %}


</main>
</body>
</html>

homework_10/quotes/templates/quotes/quote.html
{% extends "quotes/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotes:quote' %}">
    {% csrf_token %}
    <div style="padding: 15px">
        <label> Quote description:
            {{ form.description }}
        </label>
        <span>{{ form.errors.description }}</span>
    </div>
    <div style="padding: 15px">
        <label> Select tags:
            <select name="tags" multiple="multiple" required>
                {% for tag in tags %}
                <option value="{{tag.name}}">{{tag.name}}</option>
                {% endfor %}
            </select>
        </label>
    </div>
    <div style="padding: 15px">
        <label> Select author:
            <select name="authors" multiple="multiple" required>
                {% for author in authors %}
                <option value="{{author.full_name}}">{{author.full_name}}</option>
                {% endfor %}
            </select>
        </label>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>
{% endblock %}

homework_10/quotes/templates/quotes/quote_container.html
{% load extract_tags %} 
{% for quote in quotes %}
<ul>
    <li style="list-style-type: none">
        {% if quote.done %} 
        <div class="quote_container" >
            <div class="quote-discriotion-container">
                <a class="description" href="{% url 'quotes:detail' quote.id %}">"{{ quote.description }}"</a>
                {% if request.user == quote.user %}
                <a class="quote_update_button" href="{% url 'quotes:quote_update' quote.id %}" role="button">UPDATE</a>
                <a class="quote-hide-button" href="{% url 'quotes:quote_hide' quote.id %}" role="button" class="secondary"><p>Hide from everyone</p></a>
                {% endif %}
            </div>
            <div class="tag_container">
                <p>Tags: </p>
                {% for tag in quote.tags|tags_list %}
                    <a class="search-by-tag-button" href="{%url 'quotes:search_by_tag' tag %}" role="button">{{ tag }}</a>
                {% endfor %}
                {% if request.user == quote.user %}
                <a class="quote-add-tag-button" href="{% url 'quotes:quote_add_tag' quote.id %}" role="button">Add Tag</a>
                {% endif %}
            </div>
            <div class="quote-autor-info">
                <p class="quote_author">by: {{ quote.author|author }}<a class="author-details-href" href="{% url 'quotes:author_detail' quote.author|author_id %}">(about)</a></p>
                {% if request.user == quote.user %}
                <button class="delete_quote" data-quote-id="{{ quote.id }}" onclick="confirmDelete(this.dataset.quoteId)">Delete</button>
                {% endif %}
            </div>
        </div>    
        {% else %}
            {% if request.user == quote.user %}
            <div class="quote_container" >
                <div class="quote-discriotion-container">
                    <a class="description" href="{% url 'quotes:detail' quote.id %}">"{{ quote.description }}"</a>
                    {% if request.user == quote.user %}
                    <a class="quote_update_button" href="{% url 'quotes:quote_update' quote.id %}" role="button">UPDATE</a>
                    <a class="mark_down_quote" href="{% url 'quotes:set_done' quote.id %}" role="button" > Post for all </a>
                    {% endif %}
                </div>
                <div class="tag_container">
                    <p>Tags: </p>
                    {% for tag in quote.tags|tags_list %}
                        <a class="search-by-tag-button" href="{%url 'quotes:search_by_tag' tag %}" role="button">{{ tag }}</a>
                    {% endfor %}
                    {% if request.user == quote.user %}
                    <a class="quote-add-tag-button" href="{% url 'quotes:quote_add_tag' quote.id %}" role="button">Add Tag</a>
                    {% endif %}
                </div>
                <div class="quote-autor-info">
                    <p class="quote_author">by: {{ quote.author|author }}<a class="author-details-href" href="{% url 'quotes:author_detail' quote.author|author_id %}">(about)</a></p>
                    {% if request.user == quote.user %}
                    <button class="delete_quote" data-quote-id="{{ quote.id }}" onclick="confirmDelete(this.dataset.quoteId)">Delete</button>
                    {% endif %}
                </div>
            </div>
            {% endif %} 
        {% endif %}
    </li>
</ul>
{% endfor %}

homework_10/quotes/templates/quotes/search_by_tag.html
{% extends "quotes/base.html" %} {% load extract_tags %} 

{% block content %}
{% for quote in quotes %}
    <ul>
        <li class="li">
            {% if quote.done %} 
            <div class="quote-container" >
                <div class="quote-discriotion-container">
                    <a class="description" href="{% url 'quotes:detail' quote.id %}">{{ quote.description }}</a>
                    {% if request.user == quote.user %}
                    <a class="button" href="{% url 'quotes:quote_update' quote.id %}" role="button">UPDATE</a>
                    <a class="quote-hide-button" href="{% url 'quotes:quote_hide' quote.id %}" role="button" class="secondary"><p>Hide from everyone</p></a>
                    {% endif %}
                </div>
                <div class="tag-container">
                    <p>Tags: </p>
                    {% for tag in quote.tags|tags_list %}
                        <a class="button" href="{%url 'quotes:search_by_tag' tag %}" role="button">{{ tag }}</a>
                    {% endfor %}
                    {% if request.user == quote.user %}
                    <a class="add-tag-button" href="{% url 'quotes:quote_add_tag' quote.id %}" role="button">Add Tag</a>
                    {% endif %}
                </div>
                <div class="quote-autor-info">
                    <p class="quote-author">by: {{ quote.author|author }}<a class="author-details-href" href="{% url 'quotes:author_detail' quote.author|author_id %}">(about)</a></p>
                    {% if request.user == quote.user %}
                    <button class="delete-quote" data-quote-id="{{ quote.id }}" onclick="confirmDelete(this.dataset.quoteId)">Delete</button>
                    {% endif %}
                </div>
            </div>    
            {% else %}
                {% if request.user == quote.user %}
                <div class="quote-container" >
                    <div class="quote-discriotion-container">
                        <a class="description" href="{% url 'quotes:detail' quote.id %}">{{ quote.description }}</a>
                        <a class="button" href="{% url 'quotes:quote_update' quote.id %}" role="button">UPDATE</a>
                        <a class="button" href="{% url 'quotes:set_done' quote.id %}" role="button" > Post for all </a>
                    </div>
                    <div class="tag-container">
                        <p>Tags: </p>
                        {% for tag in quote.tags|tags_list %}
                            <a class="button" href="{%url 'quotes:search_by_tag' tag %}" role="button">{{ tag }}</a>
                        {% endfor %}
                        <a class="add-tag-button" href="{% url 'quotes:quote_add_tag' quote.id %}" role="button">Add Tag</a>
                    </div>
                    <div class="quote-autor-info">
                        <p class="quote-author">by: {{ quote.author|author }}<a class="author-details-href" href="{% url 'quotes:author_detail' quote.author|author_id %}">(about)</a></p>
                        <button class="delete-quote" data-quote-id="{{ quote.id }}" onclick="confirmDelete(this.dataset.quoteId)">Delete</button>
                    </div>
                </div>
                {% endif %} 
            {% endif %}
        </li>
    </ul>
    {% endfor %}
    <footer>
        <div>
            {% if quotes.has_previous %}
            <a href="?page=1" role="button">First</a>
            <a href="?page={{ quotes.previous_page_number }}" role="button">Previous</a>
            {% endif %}
            <span style="padding-left: 15px; padding-right: 15px">Page {{ quotes.number }} of {{ quotes.paginator.num_pages }}</span>
            {% if quotes.has_next %}
            <a href="?page={{ quotes.next_page_number }}" role="button">Next</a>
            <a href="?page={{ quotes.paginator.num_pages }}" role="button">Last</a>
            {% endif %}
        </div>
    </footer>

{% endblock %}

homework_10/quotes/templates/quotes/tag.html
{% extends "quotes/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotes:tag' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Enter the tag name:
            {{form.name}}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}